"""
Alias territoriales IDEAM confirmados contra DIVIPOLA.

Este catálogo contiene únicamente asociaciones explícitas y auditables.
No se permite inferencia difusa ni asignación probabilística.
"""

from __future__ import annotations

from vigia.dominio.territorio import AliasTerritorial

ALIAS_IDEAM: tuple[AliasTerritorial, ...] = (
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Bogotá",
        nombre_fuente="Bogotá, D.C",
        codigo_divipola="11001",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Valle Del Cauca",
        nombre_fuente="Cali",
        codigo_divipola="76001",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Valle Del Cauca",
        nombre_fuente="Buga",
        codigo_divipola="76111",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Norte De Santander",
        nombre_fuente="Cúcuta",
        codigo_divipola="54001",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Valle Del Cauca",
        nombre_fuente="Calima (El Darién)",
        codigo_divipola="76126",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Cauca",
        nombre_fuente="Puracé (Coconuco)",
        codigo_divipola="19585",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Cundinamarca",
        nombre_fuente="Ubaté",
        codigo_divipola="25843",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Antioquia",
        nombre_fuente="Carmen De Viboral",
        codigo_divipola="05148",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Antioquia",
        nombre_fuente="Santuario",
        codigo_divipola="05697",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Antioquia",
        nombre_fuente="San Vicente",
        codigo_divipola="05674",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Cauca",
        nombre_fuente="Piendamó",
        codigo_divipola="19548",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Boyacá",
        nombre_fuente="Guicán",
        codigo_divipola="15332",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Cauca",
        nombre_fuente="López",
        codigo_divipola="19418",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Cauca",
        nombre_fuente="Patía (El Bordo)",
        codigo_divipola="19532",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Nariño",
        nombre_fuente="Tumaco",
        codigo_divipola="52835",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Antioquia",
        nombre_fuente="Yondó (Casabe)",
        codigo_divipola="05893",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Tolima",
        nombre_fuente="Mariquita",
        codigo_divipola="73443",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Antioquia",
        nombre_fuente="San Andrés",
        codigo_divipola="05647",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Tolima",
        nombre_fuente="Armero (Guayabal)",
        codigo_divipola="73055",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Boyacá",
        nombre_fuente="Villa De Leiva",
        codigo_divipola="15407",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Choco",
        nombre_fuente="Bojayá (Bellavista)",
        codigo_divipola="27099",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Choco",
        nombre_fuente="Carmen Del Darién  (Curbaradó)",
        codigo_divipola="27150",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Choco",
        nombre_fuente="Medio Atrato (Beté)",
        codigo_divipola="27425",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Magdalena",
        nombre_fuente="Ariguaní (El Dificil)",
        codigo_divipola="47058",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Nariño",
        nombre_fuente="Los Andes (Sotomayor)",
        codigo_divipola="52418",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Amazonas",
        nombre_fuente="Mirití-Paraná (Campoamor)",
        codigo_divipola="91460",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Cauca",
        nombre_fuente="Páez (Belalcázar)",
        codigo_divipola="19517",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Cauca",
        nombre_fuente="Sotará (Paispamba)",
        codigo_divipola="19760",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Choco",
        nombre_fuente="Bahía Solano (Mutis)",
        codigo_divipola="27075",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Choco",
        nombre_fuente="Rio Quito (Paimadó)",
        codigo_divipola="27600",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Nariño",
        nombre_fuente="El Tablón",
        codigo_divipola="52258",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Nariño",
        nombre_fuente="Magüí (Payán)",
        codigo_divipola="52427",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Bolivar",
        nombre_fuente="Tiquisio (Puerto Rico)",
        codigo_divipola="13810",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Caqueta",
        nombre_fuente="Montañita",
        codigo_divipola="18410",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Choco",
        nombre_fuente="El Cantón Del San Pablo (Managrú)",
        codigo_divipola="27135",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Choco",
        nombre_fuente="Rio Iró (Santa Rita)",
        codigo_divipola="27580",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Choco",
        nombre_fuente="Unión Panamericana ( Animas)",
        codigo_divipola="27810",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Nariño",
        nombre_fuente="Arboleda (Berruecos)",
        codigo_divipola="52051",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Nariño",
        nombre_fuente="Colón (Génova)",
        codigo_divipola="52203",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Nariño",
        nombre_fuente="Cuaspud (Carlosama)",
        codigo_divipola="52224",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Nariño",
        nombre_fuente="Francisco Pizarro (Salahonda)",
        codigo_divipola="52520",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Nariño",
        nombre_fuente="Mallama (Piedrancha)",
        codigo_divipola="52435",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Nariño",
        nombre_fuente="Roberto Payán (San José)",
        codigo_divipola="52621",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Putumayo",
        nombre_fuente="San Miguel (La Dorada)",
        codigo_divipola="86757",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Putumayo",
        nombre_fuente="Valle Del Guamuez (La Hormiga)",
        codigo_divipola="86865",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Sucre",
        nombre_fuente="San Juan De Betulia (Betulia)",
        codigo_divipola="70702",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Sucre",
        nombre_fuente="Tolú",
        codigo_divipola="70820",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Antioquia",
        nombre_fuente="Don Matías",
        codigo_divipola="05237",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Bolivar",
        nombre_fuente="Mompós",
        codigo_divipola="13468",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Bolivar",
        nombre_fuente="Ríoviejo",
        codigo_divipola="13600",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Boyacá",
        nombre_fuente="Pisva",
        codigo_divipola="15550",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Cesar",
        nombre_fuente="Becerrill",
        codigo_divipola="20045",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Choco",
        nombre_fuente="Atrato (Yuto)",
        codigo_divipola="27050",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Choco",
        nombre_fuente="El Carmen",
        codigo_divipola="27245",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Choco",
        nombre_fuente="El Litoral Del San Juán (Docordó)",
        codigo_divipola="27250",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Guainía",
        nombre_fuente="Barranco Mina",
        codigo_divipola="94343",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="La Guajira",
        nombre_fuente="Hato Nuevo",
        codigo_divipola="44378",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Magdalena",
        nombre_fuente="Pivijai",
        codigo_divipola="47551",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Nariño",
        nombre_fuente="Santa Cruz (Guachavés)",
        codigo_divipola="52699",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Santander",
        nombre_fuente="El Carmen",
        codigo_divipola="68235",
    ),
    AliasTerritorial(
        fuente="IDEAM",
        departamento_fuente="Sucre",
        nombre_fuente="Tolú Viejo",
        codigo_divipola="70823",
    ),
)
